name: tool_mobile
description: Flutter Tools' base plus mobile. Use to create command line tools.
version: 3.0.0
homepage: https://github.com/mmcc007/tool_mobile

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tool_base:
    git: https://github.com/starshipcoder/tool_base

dev_dependencies:
  mockito: ^5.0.16
  pedantic: ^1.0.0
  test: ^1.16.6

dependency_overrides:
  tool_base:
    git: https://github.com/starshipcoder/tool_base
